name: Convert PDFs to Excel

on:
  push:
    paths:
      - 'price-pdfs/**'
      - 'convert_pdfs_to_excel.py'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # ⛔ disables default GitHub token to avoid conflicts

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pdfplumber pandas openpyxl

      - name: Convert PDFs to Excel
        run: python convert_pdfs_to_excel.py

      - name: Commit Excel file
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
        run: |
          set -e  # Fail on error
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add "*.xlsx"
          git commit -m "Auto-update master Excel from PDFs" || echo "Nothing to commit"
          git remote set-url origin https://x-access-token:${GH_PAT}@github.com/raj54669/mahindra-pricing-data.git
          git push origin HEAD:main
